#version 450

layout (push_constant) uniform parameter
{
    uint ne;
    uint ne00; uint ne01; uint ne02; uint ne03; uint nb00; uint nb01; uint nb02; uint nb03;
    uint ne10; uint ne11; uint ne12; uint ne13; uint nb10; uint nb11; uint nb12; uint nb13;
    uint a_offset;
    uint d_offset;
} p;

layout (binding = 0) readonly buffer A { float data_a[]; };
layout (binding = 1) writeonly buffer D { float data_d[]; };

const uint tile_size = 16;

layout(local_size_x = tile_size, local_size_y = tile_size, local_size_z = 1) in;

shared float tile[tile_size][tile_size + 1];

void main() {
    const uint read_row = gl_WorkGroupID.y * tile_size + gl_LocalInvocationID.y;
    const uint read_col = gl_WorkGroupID.x * tile_size + gl_LocalInvocationID.x;

    if (read_row < p.ne00 && read_col < p.ne01) {
        tile[gl_LocalInvocationID.y][gl_LocalInvocationID.x] =
            data_a[p.a_offset + read_row * p.nb00 + read_col * p.nb01];
    }

    barrier();

    const uint write_row = gl_WorkGroupID.y * tile_size + gl_LocalInvocationID.x;
    const uint write_col = gl_WorkGroupID.x * tile_size + gl_LocalInvocationID.y;

    if (write_row < p.ne10 && write_col < p.ne11) {
        data_d[p.d_offset + write_col * p.nb11 + write_row * p.nb10] =
            tile[gl_LocalInvocationID.x][gl_LocalInvocationID.y];
    }
}
